### ISSUE TITLE
Include the name of the MusicXML file in the NAME attribute

### ISSUE THREAD

**Issue by maccallum** [HfMT-ZM4/musicxml2jmsl#11]
Check to see if we have access to the name of the file from within the MusicXML doc. Pretty sure we don't, so this would have to be done as an additional step outside of the transcoder.

**Comment by computermusik** [comment]
Hi John,

I looked at my code again and it turns out that this fix is not necessary as I can get the file name from the opendialog object.

g

**Comment by maccallum** [comment]
Cool, closing
